apiversion: app/v1
kind: Deployment
metadata:
  name: my-backend-app
  labels:
    app: three-tier
spec:
  replica: 3
  selector:
    matchlabels:
      labels:
        app: three-tier
  template:
    metadata:
      labels:
        app: three-tier
    spec:
      container:
        - name: my-nginx
          image:
          ports:
            containerPort: 80
-----------------

apiVersion: app/v1
kind: Service
metadata:
  name: three-tier-service
  labels:
    app: three-tier
spec:
  selector:
    app: three-tier
  ports:
    - name: http
      port: 80
      containerPort: 80
      targetPort: 32456
  
